# Generated by Django 5.2.4 on 2025-07-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=100)),
                ('campaign_name', models.CharField(max_length=255)),
                ('cluster', models.IntegerField()),
                ('recommendation', models.TextField()),
                ('cost', models.FloatField()),
                ('revenue', models.FloatField()),
                ('profit', models.FloatField()),
                ('clicks', models.IntegerField()),
                ('conversions', models.IntegerField()),
                ('conversion_rate', models.FloatField()),
                ('roi', models.FloatField()),
                ('cpc', models.FloatField()),
                ('profit_margin', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
