# Generated by Django 5.2.4 on 2025-07-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_campaign_campaign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_id',
            field=models.CharField(max_length=100),
        ),
    ]
