# Generated by Django 5.2.4 on 2025-07-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_campaign_campaign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
