# Generated by Django 5.2.4 on 2025-07-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_campaign_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_campaign_id', models.IntegerField()),
                ('fb_adset_id', models.IntegerField()),
                ('fb_campaign_name', models.CharField(max_length=255)),
                ('cost', models.FloatField()),
                ('revenue', models.FloatField()),
                ('profit', models.FloatField()),
                ('clicks', models.IntegerField()),
                ('campaign_unique_clicks', models.IntegerField()),
                ('conversions', models.IntegerField()),
                ('roi_confirmed', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('lp_clicks', models.IntegerField()),
                ('cr', models.FloatField()),
                ('lp_ctr', models.FloatField()),
                ('sub_id_2', models.CharField(max_length=255)),
                ('sub_id_3', models.CharField(max_length=255)),
                ('sub_id_5', models.CharField(max_length=255)),
                ('sub_id_6', models.CharField(max_length=255)),
                ('log_revenue', models.FloatField()),
                ('log_cr', models.FloatField()),
                ('cluster', models.IntegerField()),
                ('recommendation', models.CharField(max_length=255)),
                ('urgency', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fb_adset_id'], name='api_campaig_fb_adse_d97156_idx'), models.Index(fields=['sub_id_2'], name='api_campaig_sub_id__6ee1cf_idx')],
            },
        ),
    ]
