# Generated by Django 5.2.4 on 2025-07-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_campaignad'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignad',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaignad',
            name='fb_adset_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='campaignad',
            name='log_cr',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignad',
            name='log_revenue',
            field=models.FloatField(default=0),
        ),
    ]
