# Generated by Django 5.2.4 on 2025-07-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_campaignad_reason_alter_campaignad_fb_adset_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignAdSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id_6', models.CharField(max_length=255)),
                ('sub_id_5', models.CharField(max_length=255)),
                ('sub_id_2', models.CharField(max_length=50)),
                ('sub_id_3', models.CharField(max_length=50)),
                ('day', models.DateField()),
                ('clicks', models.PositiveIntegerField()),
                ('lp_clicks', models.PositiveIntegerField()),
                ('lp_ctr', models.FloatField()),
                ('cr', models.FloatField()),
                ('cost', models.FloatField()),
                ('campaign_unique_clicks', models.PositiveIntegerField()),
                ('conversions', models.PositiveIntegerField()),
                ('roi_confirmed', models.FloatField()),
                ('revenue', models.FloatField()),
                ('profit', models.FloatField()),
                ('revenue_to_cost_ratio', models.FloatField()),
                ('conversion_rate', models.FloatField()),
                ('profit_margin', models.FloatField()),
                ('cluster', models.IntegerField()),
                ('recommendation', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('priority', models.IntegerField()),
                ('urgent', models.BooleanField(default=False)),
                ('action_needed', models.BooleanField(default=False)),
                ('potential_impact', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CampaignAd',
        ),
    ]
