# Generated by Django 5.2.4 on 2025-07-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_campaignadset_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSetTimeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id_6', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_id_5', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_id_2', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_id_3', models.CharField(blank=True, max_length=255, null=True)),
                ('day', models.DateField(blank=True, null=True)),
                ('clicks', models.IntegerField(default=0)),
                ('lp_clicks', models.IntegerField(default=0)),
                ('lp_ctr', models.FloatField(default=0.0)),
                ('cr', models.FloatField(default=0.0)),
                ('cost', models.FloatField(default=0.0)),
                ('campaign_unique_clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('roi_confirmed', models.FloatField(default=0.0)),
                ('revenue', models.FloatField(default=0.0)),
                ('profit', models.FloatField(default=0.0)),
                ('revenue_to_cost_ratio', models.FloatField(default=0.0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('profit_margin', models.FloatField(default=0.0)),
                ('cluster', models.IntegerField(default=-1)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('urgent', models.BooleanField(default=False)),
                ('action_needed', models.BooleanField(default=False)),
                ('potential_impact', models.FloatField(default=0.0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
